### ISSUE TITLE
[Feature Request]: SVG/EPS preview

### ISSUE THREAD

**Issue by UmutHasanoglu** [TagStudioDev/TagStudio#477] opened 2024-09-09 05:19 UTC
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/docs/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### Description

It would be nice if it could preview svg and eps image files.

**Comment by CyanVoxel** [comment] 2024-09-09 05:21
Duplicate of #65, and there's an open pull request for this already: #442

**Closed by CyanVoxel** 2024-09-09 05:21 UTC
Labels: Type: Duplicate, Type: Enhancement
