### ISSUE TITLE
[Bug]:  Add parent tag box does not show any tags by default

### ISSUE THREAD

**Issue by ZophiaMarie** [TagStudioDev/TagStudio#278] opened 2024-06-12 07:27 UTC
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### TagStudio Version

Alpha v9.3.0

### Operating System & Version

WIndows 11

### Description

The Add parent tags box is completely devoid of tags till you search for them. 
![TagStudio_z19ojsVEKf](https://github.com/TagStudioDev/TagStudio/assets/110948107/9f6ca669-bcd0-4397-af3e-43b6e5915fc6)

### Expected Behavior

The box to be populated with tags

### Steps to Reproduce

1. Make a new tag or edit an old one
2. Click the plus to add a parent tag

**Comment by yedpodtrzitko** [comment] 2024-06-13 04:21
this looks like regression introduced in #113 [here](https://github.com/TagStudioDev/TagStudio/pull/113/files#diff-79d3e30e97dfebfc97c01501253c1f9d7754f32284409ffca071817def18dd20L71)

**Comment by CyanVoxel** [comment] 2024-07-25 07:57
Independently fixed in #328

**Closed by CyanVoxel** 2024-07-25 07:57 UTC
Labels: Type: Bug, Type: QoL, Type: UI/UX, Priority: Medium, TagStudio: Tags
