### ISSUE TITLE
[Bug]: Nix GPU Acceleration / AMD GPU Support

### ISSUE THREAD

**Issue by zierf** [TagStudioDev/TagStudio#417] opened 2024-08-29 23:45 UTC
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### TagStudio Version

main #cb4798b

### Operating System & Version

NixOS 24.11 (Vicuna), 24.11.20240818.8a33541 | nixpkgs-unstable#8a33541 | KDE

### Description

It looks like Nix Flake is missing a `qt6.full` dependency listing for video playback, which means the video preview remains empty (Wayland and X11).

![Screenshot_20240830_000755](https://github.com/user-attachments/assets/210c8199-0a8f-4e33-9cd5-a0d307023b80)

This is also noted in the console log at the beginning, but when clicking a video only `Playing …` appears as normal and no further error message.
```SH
No QtMultimedia backends found. Only QMediaDevices, QAudioDevice, QSoundEffect, QAudioSink, and QAudioSource are available.
Failed to initialize QMediaPlayer "Not available"
Failed to create QVideoSink "Not available"
# ...
Playing /MEDIA_PATH/big_buck_bunny_1080p_h264.mov
```

After adding the `qt6.full` dependency, video playback in the preview window works for X11.

Video playback would work under Wayland too, but only using the CPU.
So an additional entry for `wayland` libraries in the library search path is needed.

<details>
<summary>Without the Wayland libraries, this error message would appear.</summary>

```SH
qt.qpa.wayland: EGL not available
# ...
Playing /MEDIA_PATH/big_buck_bunny_1080p_h264.mov
QRhi* initializeRHI(QRhi*) : No RHI backend. Using CPU conversion.
```

Running _QT Creator_ results in a similar message.
```SH
qt.qpa.wayland: EGL not available
Warning: fallback to QtQuick software backend.
```

![Screenshot_20240830_011211](https://github.com/user-attachments/assets/912df7a7-e427-4a93-983a-66985efbecc1)
</details>

The only ugly thing that remains is that _PySide6_ seems to rely only on VDPAU for hardware-accelerated video playback and apparently still wants to use a hard-coded NVIDIA library.

```SH
Playing /MEDIA_PATH/big_buck_bunny_1080p_h264.mov
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
```

Fortunately, the driver to be used can at least be overridden for the free AMD driver with the environment variable `VDPAU_DRIVER=radeonsi`, which provides a translation layer for VDPAU to VA-API.

<details>
<summary>Use VDPAU for AMD driver.</summary>

__AMD driver provides VA-API out of the box:__
```SH
$> nix shell nixpkgs#libva-utils -c vainfo

Trying display: wayland
libva info: VA-API version 1.22.0
libva info: Trying to open /run/opengl-driver/lib/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.22 (libva 2.22.0)
vainfo: Driver version: Mesa Gallium driver 24.1.5 for AMD Radeon RX 6900 XT (radeonsi, navi21, LLVM 18.1.8, DRM 3.57, 6.10.5-xanmod1)
# ...
```

__No VDPAU support without overriding the proper driver:__
```SH
$> nix shell nixpkgs#vdpauinfo -c vdpauinfo

display: :0   screen: 0
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
Error creating VDPAU device: 1
```

__Overriding the VDPAU driver to use VDPAU on an AMD GPU:__
```SH
$> VDPAU_DRIVER=radeonsi nix shell nixpkgs#vdpauinfo -c vdpauinfo

display: :0   screen: 0
API version: 1
Information string: G3DVL VDPAU Driver Shared Library version 1.0

Video surface:
# ...
```
</details>

---

I can submit a pull request that enables hardware acceleration for the Nix-Flake.

The free AMD driver should be detected and the VDPAU driver will be overwritten, provided the user has not already explicitly set the environment variable `VDPAU_DRIVER`. For Nvidia GPUs, the variable simply remains unset.

### Expected Behavior

Clicking on a video file should play the video in the preview window on the right.

### Steps to Reproduce

1. Open TagStudio
2. Click on a video file

### Logs

<details>
<summary>Branch main (Commit #cb4798b)</summary>

```SH
$> tagstudio

[ResourceManager] 4 resources registered
[QT DRIVER] Config File not specified, defaulting to /home/USER/.config/TagStudio/TagStudio.ini
No QtMultimedia backends found. Only QMediaDevices, QAudioDevice, QSoundEffect, QAudioSink, and QAudioSource are available.
Failed to initialize QMediaPlayer "Not available"
Failed to create QVideoSink "Not available"
Calling NavForward with Content:False, Index:0, PageCount:0
[ENTRY PANEL] UPDATE WIDGETS ([])
[LIBRARY] Extension list loaded in 0.000 seconds
[LIBRARY] Tags loaded in 0.000 seconds
[LIBRARY] Entries loaded in 0.000 seconds
[LIBRARY] Collations loaded in 0.000 seconds
[ENTRY PANEL] UPDATE WIDGETS ([])
Query:, Frame: 0,  Length: 140
Calling NavForward with Content:(<ItemType.ENTRY: 0>, 139), Index:0, PageCount:1
[UPDATE CONTAINER] Setting tags updated slot
[ENTRY PANEL] UPDATE WIDGETS ([(<ItemType.ENTRY: 0>, 5)])
Playing /MEDIA_PATH/big_buck_bunny_1080p_h264.mov
Saving Library...
[LIBRARY] Saving Library to Disk...
[LIBRARY] Formatting Tags to JSON...
[LIBRARY] Formatting Entries to JSON...
[LIBRARY] Formatting Collations to JSON...
[LIBRARY] Done Formatting to JSON!
[LIBRARY] Library saved to disk in 0.002 seconds
[SHUTDOWN] Ending Thumbnail Threads...
```
</details>

<details>
<summary>Adding qt6.full to nativeBuildInputs under Wayland</summary>

```SH
$> tagstudio

[ResourceManager] 4 resources registered
[QT DRIVER] Config File not specified, defaulting to /home/USER/.config/TagStudio/TagStudio.ini
qt.qpa.wayland: EGL not available
Calling NavForward with Content:False, Index:0, PageCount:0
[ENTRY PANEL] UPDATE WIDGETS ([])
[LIBRARY] Extension list loaded in 0.000 seconds
[LIBRARY] Tags loaded in 0.000 seconds
[LIBRARY] Entries loaded in 0.000 seconds
[LIBRARY] Collations loaded in 0.000 seconds
[ENTRY PANEL] UPDATE WIDGETS ([])
Query:, Frame: 0,  Length: 140
Calling NavForward with Content:(<ItemType.ENTRY: 0>, 139), Index:0, PageCount:1
[UPDATE CONTAINER] Setting tags updated slot
[ENTRY PANEL] UPDATE WIDGETS ([(<ItemType.ENTRY: 0>, 5)])
Playing /MEDIA_PATH/big_buck_bunny_1080p_h264.mov
QRhi* initializeRHI(QRhi*) : No RHI backend. Using CPU conversion.
Saving Library...
[LIBRARY] Saving Library to Disk...
[LIBRARY] Formatting Tags to JSON...
[LIBRARY] Formatting Entries to JSON...
[LIBRARY] Formatting Collations to JSON...
[LIBRARY] Done Formatting to JSON!
[LIBRARY] Library saved to disk in 0.002 seconds
[SHUTDOWN] Ending Thumbnail Threads...
```
</details>

<details>
<summary>qt6.full and Wayland libraries</summary>

```SH
$> tagstudio

[ResourceManager] 4 resources registered
[QT DRIVER] Config File not specified, defaulting to /home/USER/.config/TagStudio/TagStudio.ini
Calling NavForward with Content:False, Index:0, PageCount:0
[ENTRY PANEL] UPDATE WIDGETS ([])
[LIBRARY] Extension list loaded in 0.000 seconds
[LIBRARY] Tags loaded in 0.000 seconds
[LIBRARY] Entries loaded in 0.000 seconds
[LIBRARY] Collations loaded in 0.000 seconds
[ENTRY PANEL] UPDATE WIDGETS ([])
Query:, Frame: 0,  Length: 140
Calling NavForward with Content:(<ItemType.ENTRY: 0>, 139), Index:0, PageCount:1
[UPDATE CONTAINER] Setting tags updated slot
[ENTRY PANEL] UPDATE WIDGETS ([(<ItemType.ENTRY: 0>, 5)])
Playing /MEDIA_PATH/big_buck_bunny_1080p_h264.mov
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
Saving Library...
[LIBRARY] Saving Library to Disk...
[LIBRARY] Formatting Tags to JSON...
[LIBRARY] Formatting Entries to JSON...
[LIBRARY] Formatting Collations to JSON...
[LIBRARY] Done Formatting to JSON!
[LIBRARY] Library saved to disk in 0.001 seconds
[SHUTDOWN] Ending Thumbnail Threads...
```
</details>

**Comment by xarvex** [comment] 2024-08-30 00:17
I was able to resolve launching the application as a Wayland application with the libraries by adding `wayland`, but I am a little confused about `qt6.full` as that is already part of the library path. Though, I get the same issue of not having media playing. In my testing reverting to 6.7.0 of Qt and PySide was the "fix" to that (though those versions come with their set of separate issues).
Would love to hear more. Also, I am hesitant about the environment variable as that tends to be something that should be set on the user's system. Possibly, we could default it if not set to `va_gl` so VAAPI uses its translation layer with VDPAU.

**Comment by xarvex** [comment] 2024-08-30 00:26
I seem to have fixed the issue by spotting `libXrandr.so` failing to load, I will do a little more testing but given that seems to have done it you will probably see a push in the next few minutes.

**Comment by xarvex** [comment] 2024-08-30 00:42
Marking this as closed because `VDPAU_DRIVER` does seem to be something that is configured by the user based on their hardware/drivers and exact setup. You can see the [Arch wiki](https://wiki.archlinux.org/title/Hardware_video_acceleration#Configuring_VA-API) for what lead to my rationale on that.
Other than that, I added `wayland` and `libXrandr` which seems to have done it.

**Comment by zierf** [comment] 2024-08-30 02:48
I only thought about overwriting the environment variable `VDPAU_DRIVER` if it had not already been overwritten manually, in order to make it easier for new users to get started. If someone deliberately set it themselves, then it will not be added automatically.

My [Branch hw_acceleration](https://github.com/zierf/TagStudio/commit/af33ff10cfa4876015968e56b95b6259a9ecc23e) would have been my suggestion for the pull request.

But if you don't look more closely in the terminal and then do some further research, you won't necessarily know all of that.

Pure Nvidia systems should not list `radeonsi` as a driver in `vainfo` anyway. AMD systems with an open driver would also have been covered by my suggestion and I was now able to test that. If someone had added a switch for Intel in the future, that would have saved users having to do manual follow-up work.

Ideally, the best thing would be to simply use VA-API instead of VDPAU if it is available too or auto-discover the AMD VDPAU adapter driver, but I haven't figured out why _Pyside6_ always only requests VDPAU and how VA-API could be allowed too.

---

Apparently your fix with `xorg.libXrandr` enables video playback for me too.
However, two new errors have been added by _ffmpeg_ due to missing libraries.
Somehow a library for VA-API is sought here, although _Pyside6_ only requests VDPAU later.

<details>
<summary>ffmpeg errors</summary>

```SH
$> tagstudio

[ResourceManager] 4 resources registered
[QT DRIVER] Config File not specified, defaulting to /home/USER/.config/TagStudio/TagStudio.ini
qt.multimedia.ffmpeg.libsymbolsresolver: Couldn't load OpenSsl library
qt.multimedia.ffmpeg.libsymbolsresolver: Couldn't load VAAPI library
Calling NavForward with Content:False, Index:0, PageCount:0
[ENTRY PANEL] UPDATE WIDGETS ([])
[LIBRARY] Extension list loaded in 0.000 seconds
[LIBRARY] Tags loaded in 0.000 seconds
[LIBRARY] Entries loaded in 0.000 seconds
[LIBRARY] Collations loaded in 0.000 seconds
[ENTRY PANEL] UPDATE WIDGETS ([])
Query:, Frame: 0,  Length: 140
Calling NavForward with Content:(<ItemType.ENTRY: 0>, 139), Index:0, PageCount:1
[UPDATE CONTAINER] Setting tags updated slot
[ENTRY PANEL] UPDATE WIDGETS ([(<ItemType.ENTRY: 0>, 5)])
Playing /MEDIA_PATH/big_buck_bunny_1080p_h264.mov
Saving Library...
[LIBRARY] Saving Library to Disk...
[LIBRARY] Formatting Tags to JSON...
[LIBRARY] Formatting Entries to JSON...
[LIBRARY] Formatting Collations to JSON...
[LIBRARY] Done Formatting to JSON!
[LIBRARY] Library saved to disk in 0.002 seconds
[SHUTDOWN] Ending Thumbnail Threads...
```
</details>

If I add `qt6.full` to the `buildInputs` again, like in [my proposal](https://github.com/zierf/TagStudio/commit/af33ff10cfa4876015968e56b95b6259a9ecc23e), the error messages disappear.
It is probably also possible to list more fine-grained dependencies instead of just `qt6.full`.

<details>
<summary>No error with qt6.full</summary>

```SH
$> tagstudio
[ResourceManager] 4 resources registered
[QT DRIVER] Config File not specified, defaulting to /home/USER/.config/TagStudio/TagStudio.ini
Calling NavForward with Content:False, Index:0, PageCount:0
[ENTRY PANEL] UPDATE WIDGETS ([])
[LIBRARY] Extension list loaded in 0.000 seconds
[LIBRARY] Tags loaded in 0.000 seconds
[LIBRARY] Entries loaded in 0.000 seconds
[LIBRARY] Collations loaded in 0.000 seconds
[ENTRY PANEL] UPDATE WIDGETS ([])
Query:, Frame: 0,  Length: 140
Calling NavForward with Content:(<ItemType.ENTRY: 0>, 139), Index:0, PageCount:1
[UPDATE CONTAINER] Setting tags updated slot
[ENTRY PANEL] UPDATE WIDGETS ([(<ItemType.ENTRY: 0>, 5)])
Playing /MEDIA_PATH/big_buck_bunny_1080p_h264.mov
Saving Library...
[LIBRARY] Saving Library to Disk...
[LIBRARY] Formatting Tags to JSON...
[LIBRARY] Formatting Entries to JSON...
[LIBRARY] Formatting Collations to JSON...
[LIBRARY] Done Formatting to JSON!
[LIBRARY] Library saved to disk in 0.001 seconds
[SHUTDOWN] Ending Thumbnail Threads...
```
</details>

Having to list the package several times could possibly be due to Python. But I'm not entirely sure. The discourse [Use buildInputs or nativeBuildInputs for nix-shell?](https://discourse.nixos.org/t/use-buildinputs-or-nativebuildinputs-for-nix-shell/8464/2) has a comment that might explain it:
"_There’s some cases like python where you may need to list them both as a nativeBuildInputs and as a buildInput, if the package needs to run python during build and will link against it._"

---

I also experimented a bit with a [Branch dependency_cleanup](https://github.com/zierf/TagStudio/commit/e2f6a3371aafe24bb8ea3b0a7048e234a672338b) to see which dependencies really seem to be necessary.

Apart from the aforementioned addition of `qt6.full`, a lot of things could probably be removed without breaking anything at first glance.

Almost all packages in the `packages` section can be removed and _TagStudio_ still starts and the hardware-accelerated video playback still works correctly. Likewise, the _QT Creator_ (apparently requires a `cmake` executable) can at least be started without any errors.

You may want to keep packages like `mypy` and `ruff` so that the development environment can also call their executables. With the `binutils` and `coreutils` I could imagine that _QT Creator_ would want to call some executables from them later on when used. But due to the pure nature of the _devenv_ most Unix commands like `ls`, `ln`, `mv`, etc. ... are actually available anyway, I would even go so far as to say even in pure Nix Flakes.

I think that the _QT Creator_ brings all its important library dependencies with it and only the executables called at runtime need to be listed.

**Comment by xarvex** [comment] 2024-08-30 03:12
Ok, I see what you were going for now, I didn't realize you were mentioning specifically about the `runCommand`'s build inputs, I had missed that detail.

As well, I curiously don't get any errors or messages about VAAPI or VDPAU, I imagine that is related to my Intel iGPU. That is, until I tried the adjustments now that I could look at your branch. Then I did get errors related to VDPAU loading, which I resolved by setting `VDPAU_DRIVER` to `va_gl`. I suppose something was silently failing somewhere along the line.

```patch
index 50689b6..a944b09 100644
--- a/flake.nix
+++ b/flake.nix
@@ -88,10 +88,15 @@
                     setQtEnv = pkgs.runCommand "set-qt-env"
                       {
                         buildInputs = with qt6Pkgs.qt6; [
-                          qtbase # Needed by wrapQtAppsHook.
-                          wrapQtAppsHook
+                          qtbase
+                          full
                         ];
-                        nativeBuildInputs = with pkgs; [ makeShellWrapper ];
+                        nativeBuildInputs = (with pkgs; [
+                          makeShellWrapper
+                        ])
+                        ++ (with qt6Pkgs.qt6; [
+                          wrapQtAppsHook
+                        ]);
                       }
                       ''
                         makeShellWrapper "$(type -p sh)" "$out" "''${qtWrapperArgs[@]}"
@@ -126,7 +131,6 @@
                       stdenv.cc.cc.lib
                       wayland
                       xorg.libxcb
-                      xorg.libXrandr
                       zlib
                       zstd
                     ])
```

As well, I've been meaning to do the cleanup of dependencies. A lot of this flake stemmed from an old unmaintained one, and I didn't want to change too many things at once, and tried to essentially "convert" into a devenv/direnv setup for ease that would come later down the line. Fantastic to see that you've been going at that.

Now that I look at your solution for setting `VDPAU_DRIVER`, doesn't seem all too bad to maintain. If you wanna go ahead and make a PR I can add onto it with what works for Intel and NVIDIA and get that merged.

**Comment by zierf** [comment] 2024-08-30 03:54
Even better, based on your changes, I found a way to make QT6 automatically use the VA-API instead of VDPAU.

This means we don't need any manual adjustments or overrides for AMD or Intel systems and `qt6.full` can be omitted entirely.

__You just need to add the `libva` and `openssl` libraries in addition to your previously added `xorg.libXrandr`.__

Who would have thought that `libXrandr` of all things would also enable basic video playback. Of course, it is one of the few libraries that I did not see as a possible solution during my research and of course didn't try it out.

The package for `libva` looks like it's for Intel only. But apart from the fact that it also works with my AMD GPU, you can also see support for other manufacturers and driver combinations in the [va_drm_utils.c](https://github.com/intel/libva/blob/01153523f25ac703e7ce2afc0023788a90f6c1bb/va/drm/va_drm_utils.c#L62-L68) (even older AMD drivers, inofficial Nvidia driver and Linux-Shell under Windows).

I wish this was all described a little more clearly and provided with better and up-to-date documentation …

---

<details>
<summary>Here the relevant logs for those interested.</summary>

```SH
$> export VDPAU_DRIVER=

$> echo $VDPAU_DRIVER
# <empty>

$> tagstudio
[ResourceManager] 4 resources registered
[QT DRIVER] Config File not specified, defaulting to /home/USER/.config/TagStudio/TagStudio.ini
Calling NavForward with Content:False, Index:0, PageCount:0
[ENTRY PANEL] UPDATE WIDGETS ([])
[LIBRARY] Extension list loaded in 0.000 seconds
[LIBRARY] Tags loaded in 0.000 seconds
[LIBRARY] Entries loaded in 0.000 seconds
[LIBRARY] Collations loaded in 0.000 seconds
[ENTRY PANEL] UPDATE WIDGETS ([])
Query:, Frame: 0,  Length: 140
Calling NavForward with Content:(<ItemType.ENTRY: 0>, 139), Index:0, PageCount:1
[UPDATE CONTAINER] Setting tags updated slot
[ENTRY PANEL] UPDATE WIDGETS ([(<ItemType.ENTRY: 0>, 5)])
Playing /MEDIA_PATH/big_buck_bunny_1080p_h264.mov
Saving Library...
[LIBRARY] Saving Library to Disk...
[LIBRARY] Formatting Tags to JSON...
[LIBRARY] Formatting Entries to JSON...
[LIBRARY] Formatting Collations to JSON...
[LIBRARY] Done Formatting to JSON!
[LIBRARY] Library saved to disk in 0.002 seconds
[SHUTDOWN] Ending Thumbnail Threads...
```
</details>

VA-API finally just works.

---

I've put all this into a [reference commit](https://github.com/zierf/TagStudio/commit/ae120a12e2cde8767c3816895bbb19bc2b4ed3e9) that you can refer to if necessary.

**Comment by xarvex** [comment] 2024-08-30 03:59
Awesome finding!! And yeah, the only reason I had discovered `libXrandr` at all was by peering into the debug logging of plugin loading, and saw it failing to load the object. Unfortunately, that was the only object that was listed as failing to load, so thats where my tracks stopped.

> I wish this was all described a little more clearly and provided with better and up-to-date documentation …

If only... myself and another individual were trying to figure out what was the cause. With the findings here, it makes me even more confused why Qt and PySide 6.7.0 resolved the issue, but I am happy to just see this fixed at all.

**Comment by xarvex** [comment] 2024-08-30 04:02
If you wanna make a quick PR I can get this merged and you can get more GitHub points. You don't even need to have an in-depth description, just provide a link to this issue and that will suffice.

**Closed** 2024-08-30 04:49 UTC
Labels: Type: Bug, Type: Installation, System: Linux

**Comment by zierf** [comment] 2024-08-30 04:51
Great, thank you!
