### ISSUE TITLE
[Feature Request] Ignore anything under a directory or in an ignore file

### ISSUE THREAD

**Issue by grepgrok** [TagStudioDev/TagStudio#158] opened 2024-05-10 05:36 UTC
I would love to be able to tag my coding projects, unfortunately, these are often large with thousands of tiny, repetitive, uninteresting files. I would love for the library search to just ignore these.

This can be somewhat automated, for example, a anything listed in a `.gitignore` can probably be ignored. Likewise, a number of project structures have a default "backups ignore these files" signal which can probably be identified.

At the bare minimum, letting the user ignore batches of files would be great.

Also, it is important to note that, if you are ignoring a directory, there may be files IN that directory which the user may want to specify as to NOT ignore.

**Comment by grepgrok** [comment] 2024-05-10 06:04
See #74

**Comment by grepgrok** [comment] 2024-05-10 07:30
Wait, I'm a dingbat. Ignoring directories not tagging them (though they are perhaps related)

**Comment by CyanVoxel** [comment] 2024-05-10 08:09
> Wait, I'm a dingbat. Ignoring directories not tagging them (though they are perhaps related)

No worries! Although, I hate to be the one to say that this is a duplicate of #14...

**Closed** 2024-05-13 21:12 UTC
Labels: duplicate

**Comment by roboticforest** [comment] 2024-12-12 01:46
> Also, it is important to note that, if you are ignoring a directory, there may be files IN that directory which the user may want to specify as to NOT ignore.

I added this in my own notes just today as I play around with and explore the program and was going to suggest it as a feature, so an important thing to cast my vote on.

The example I put in my notes was ignoring certain OS files by default, like all `desktop.ini` files, except if a user creates or customizes any themselves (like I have for my home folders) than they might want just those custom ones visible for tagging.

This could potentially be implemented as a simple exclusion list which contains folder & file extension entries, but if any item starts with some specific escape character, like say... a minus sign, than those are exceptions. Some could apply for an inclusion list too.

For example:
Say I'm working with a library made from my `~/Pictures/` directory

```
EXCLUDE
*.ini
*.bak
Some Project/
- /Wallpapers/desktop.ini
```

Here every `.ini` and `.bak` file, along with the directory `Some Project/`, but the custom `desktop.ini` within the `Wallpapers/` directory is *not* ignored.

**Comment by CyanVoxel** [comment] 2024-12-12 01:55
> > Also, it is important to note that, if you are ignoring a directory, there may be files IN that directory which the user may want to specify as to NOT ignore.
> 
> I added this in my own notes just today as I play around with and explore the program and was going to suggest it as a feature, so an important thing to cast my vote on.
> 
> The example I put in my notes was ignoring certain OS files by default, like all `desktop.ini` files, except if a user creates or customizes any themselves (like I have for my home folders) than they might want just those custom ones visible for tagging.
> 
> This could potentially be implemented as a simple exclusion list which contains folder & file extension entries, but if any item starts with some specific escape character, like say... a minus sign, than those are exceptions. Same could apply for an inclusion list too.
> 
> For example: Say I'm working with a library made from my `~/Pictures/` directory
> 
> ```
> EXCLUDE
> *.ini
> *.bak
> Some Project/
> - /Wallpapers/desktop.ini
> ```
> 
> Here every `.ini` and `.bak` file, along with the directory `Some Project/`, but the custom `desktop.ini` within the `Wallpapers/` directory is _not_ ignored.

That feature is being tracked via #624 (formerly #14 which is now stale). I saw your comment over there as well, and your use cases should be able to be accomplished via a .gitignore style glob list mentioned there.

*(also please do not comment on old closed issues, this one was closed as being a duplicate and commenting here only serves to unnecessarily notify people and fragment the discussion of present issues.)*
