### ISSUE TITLE
[Bug]: [Translation] Rewording of the File Extensions dialogue

### ISSUE THREAD

**Issue by smileyhead** [TagStudioDev/TagStudio#525] opened 2024-09-25 08:40 UTC
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/docs/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### Description

Currently, the drop-down in the File Extension dialogue is worded as the following:
> List Mode:
> - Include
> - Exclude

![image](https://github.com/user-attachments/assets/d67d2141-5b63-4da3-90d2-88b60352dbfa)

…with include and exclude being generic strings that may be used all over TagStudio. For translations (and perhaps English itself as well), it might be better to give this dialogue unique strings and word them as the following:
> Listed extensions are
> - shown
> - hidden

**Comment by CyanVoxel** [comment] 2024-09-27 04:57
I agree, they should not be marked as generic in the translations file(s). I'm actually going to mark this as a bug since it's not the intended behavior

**Comment by CyanVoxel** [comment] 2024-12-22 01:36
Fixed in f4b30c15ce834f7baf24edbb9b8b4a88e8c9c99f 👍

**Closed by CyanVoxel** 2024-12-22 01:36 UTC
Labels: Type: Bug, Type: Translation
