### ISSUE TITLE
Large file misidentified as a decompression bomb

### ISSUE THREAD

**Issue by Equinox3141** [TagStudioDev/TagStudio#164] opened 2024-05-12 11:57 UTC
There's a file in my library that can't be interacted with or shown (other than a red crossed out tag). Due to it being misinterpreted as a decompression bomb DOS attack. Warning message below.

> D:\TagStudio-main\.venv\Lib\site-packages\PIL\Image.py:3218: DecompressionBombWarning: Image size (108603828 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(

I was confused by this, so after some searching through the folder that I was looking at, I found that the file it was struggling with was a very large .png file that was about 20000x14000 px.

**Comment by Thesacraft** [comment] 2024-05-12 13:08
Hi,
This error is caused by a library and is kind of fixable:
You can suppress this error by setting `Image.MAX_IMAGE_PIXELS=None`
Or 
`IMAGE.MAX_IMAGE_PIXELS=108603829`
But i don't think it is a good idea to have safety precautions disabled or weakened in production code. But I'm not sure what others think about it.

**Comment by CyanVoxel** [comment] 2024-05-13 21:38
Fixed in #166

**Closed by CyanVoxel** 2024-05-13 21:38 UTC
Labels: bug
