### ISSUE TITLE
Subtags not working as expected?

### ISSUE THREAD

**Issue by TheChilliPL** [TagStudioDev/TagStudio#211] opened 2024-05-23 21:14 UTC
Having two tags, `A` (`tag_id:1000`) and `B` (`tag_id:1001`), with `A` having the subtag `B`¹, imagine you have files `a` and `b` with tags `A` and `B` selected respectively.
If you look for `tag_id:1000` or `tag_id:1001`, you only get one single file for each of them, despite the fact one of them should imply the other one. It makes the search function unusable

¹ Reading the documentation, I have a feeling subtag is a *terrible* name for that, as it's kinda the wrong way. “Sub-” implies part of, while it in fact specifies the tags the tag inherits its values from. Maybe it'd be better to name them “supertags” (super-, meaning above or over) or “parent tags”?

**Comment by Pheubel** [comment] 2024-05-23 21:26
I agree that the naming can be easily confusing to new users, i fell for it myself. "parent tag" is in my opinion not a bad choice for it, but i would like to also throw in an alternative option with "implied tags". The advantage to it is that it clearly states that the tags attached to the current one will act as an umbrella tag that can be searched for instead. The downside to it is that it doesn't show hierarchical relation as well, and people my create a hierarchy loop a little bit easier.

**Comment by The-Stolas** [comment] 2024-05-23 21:30
I had no problem with the search function of subtags once I understood that it is inverted, but the naming is kind of confusing. 
"Korra" needs to have a **subtag** of "Avatar", so when I search for Avatar I get everything and Korra and only Korra images if I search for her. 
It's a bit strange, because you would think Korra should be a subtag of "Avatar" (characater as a subtag of fandom), not the other way around. "Parent tag" is a more logical name in my opinion.

**Comment by CyanVoxel** [comment] 2024-05-23 21:30
Subtags will be renamed to Parent Tags in future releases, this is a change I should've made earlier if I'm being honest.

As for the id search, I'm assuming you're using the "tag_id" search that you get by clicking on the tags themselves inside the preview panel or by right clicking and selecting "Search for Tag". This is working *half* as intended, and by that I mean that the ID search is a leftover developer test that will only ever return tags with that exact ID present on them (so no parent tags) - but this shouldn't be the option presented to users when they click "Search for Tag". I can work on a patch that will correct this behavior.
![image](https://github.com/TagStudioDev/TagStudio/assets/46939827/518b1024-6786-454e-9aea-cb49ef36232f)
![image](https://github.com/TagStudioDev/TagStudio/assets/46939827/94c57fee-7e39-4632-bb2e-46006e515431)

In the meantime, searching for the tag name itself will result in the correct behavior involving parent tags.

**Comment by TheChilliPL** [comment] 2024-05-23 23:57
> Subtags will be renamed to Parent Tags in future releases, this is a change I should've made earlier if I'm being honest.
> 
> As for the id search, I'm assuming you're using the "tag_id" search that you get by clicking on the tags themselves inside the preview panel or by right clicking and selecting "Search for Tag". This is working _half_ as intended, and by that I mean that the ID search is a leftover developer test that will only ever return tags with that exact ID present on them (so no parent tags) - but this shouldn't be the option presented to users when they click "Search for Tag". I can work on a patch that will correct this behavior. ![image](https://private-user-images.githubusercontent.com/46939827/333345360-518b1024-6786-454e-9aea-cb49ef36232f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MDAxOTAsIm5iZiI6MTcxNjQ5OTg5MCwicGF0aCI6Ii80NjkzOTgyNy8zMzMzNDUzNjAtNTE4YjEwMjQtNjc4Ni00NTRlLTlhZWEtY2I0OWVmMzYyMzJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDIxMzEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjZDNjOGE3ZGMzMDAzMTEwMmI4ZGQzZjRkYWNmZTE4MWY1MTQ2YjNmYTUwNTVkYzlkYTg1MjRmNjBmZTYxOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NX1bO9h9BAPlCC0pVscCddXr9gU4AgrBoaJrizKaJPs) ![image](https://private-user-images.githubusercontent.com/46939827/333345506-94c57fee-7e39-4632-bb2e-46006e515431.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MDAxOTAsIm5iZiI6MTcxNjQ5OTg5MCwicGF0aCI6Ii80NjkzOTgyNy8zMzMzNDU1MDYtOTRjNTdmZWUtN2UzOS00NjMyLWJiMmUtNDYwMDZlNTE1NDMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDIxMzEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwYmQ2OGU2YTljNDUwMGRmN2JmNTVjYmEzOTM5ZmVhOGViN2MzZmEwNWVkZTNiNmViMmQ2NTA3ZTA3ZGQ5NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SEkgGYyHxdGg2mcfvdfXhXLxC3htJO3x_l39nHDprXQ)
> 
> In the meantime, searching for the tag name itself will result in the correct behavior involving parent tags.

Yeah, I do. In the future, might be nice to implement finding tags by some specific text syntax (e.g. `#tagname`, although it gets slightly more complicated for tags with spaces).
Also, I'm not sure if including the first parent tag in the parentheses is perfect. Surely might make sense sometimes, but often it might be arbitrary, and people could add it themselves to the tag name

**Comment by TheChilliPL** [comment] 2024-05-24 00:20
Personally I wouldn't mind having to manually name tags like `Shrek (Character)` and `Shrek (Movie)`, to be honest, though including it automatically when there's name duplicates sounds good as well.
How would that searching work with various tag categories, though? I see there's `Tags`, `Meta tags` and `Content tags`. While this distinction makes sense, wouldn't it be better to allow separate tag lists? (Or even allowing creating more of them; cause I think this distinction is hard-coded now)

**Comment by CyanVoxel** [comment] 2024-05-24 00:35
> Personally I wouldn't mind having to manually name tags like `Shrek (Character)` and `Shrek (Movie)`, to be honest, though including it automatically when there's name duplicates sounds good as well. How would that searching work with various tag categories, though? I see there's `Tags`, `Meta tags` and `Content tags`. While this distinction makes sense, wouldn't it be better to allow separate tag lists? (Or even allowing creating more of them; cause I think this distinction is hard-coded now)

The `Tags`, `Meta tags` and `Content tags` distinctions are going to change as well in a future update (sorry for so much "in the future" stuff). The plan going forward is to replace the idea of "tag fields" with the ability to mark a tag as a "category" that the UI then treats differently, creating a similar organizational distinction but with much more customization and flexibility. It should also be a lot more straightforward to use than the current system of adding a tag field -> then adding a tag to that field.

So an example of how this would look with the built-in Favorite tag would be:
- "Favorite" inherits from a built-in "Meta" tag, which is toggled as a "Category"
- This then displays the word "Meta" as a section title, similar to how tag fields are currently displayed
- The "Favorite" tag would then automatically display underneath this "section", no user intervention required.

This means that:
- Users won't have to add tag fields before adding tags
- Users don't have to worry about adding the right tag to the right tag fields anymore, as it's all automatic
- These tag categories will be fully customizable by the user, including things like display color (and icons in the future 🤞)
- If a tag inherits from multiple categories, it will automatically be displayed under all of these categories when added without any further intervention from the user

**Comment by TheChilliPL** [comment] 2024-05-24 00:42
Looking forward to all the changes. I've been waiting for such a piece of software for years, and seems it's already there. Just needs some more development 😉

**Comment by CyanVoxel** [comment] 2024-08-31 20:12
Tag ID search issued fixed in #398

**Closed by CyanVoxel** 2024-08-31 20:12 UTC
Labels: Type: Bug, TagStudio: Tags
