### ISSUE TITLE
[Bug]: certain parent and grandparent tags not showing up in searches

### ISSUE THREAD

**Issue by Treewad** [TagStudioDev/TagStudio#308] opened 2024-07-04 05:49 UTC
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### TagStudio Version

Alpha 9.3.1

### Operating System & Version

Windows 11

### Description

I was experimenting with tagging some of my saved digital art when I noticed some very strange and inconsistent interactions with certain parent tags and the search function. I'll use specific examples to make sure I don't miss any details. 

First, I created a tag for the character Princess Zelda. I named it _%princess_zelda_ and gave it the shorthand _zelda_ and the alias _princess zelda_. Then I gave it the parent tag _$tears_of_the_kingdom_, which has the shorthand _totk_ and the alias _tears of the kingdom_. Then I gave the _$tears_of_the_kingdom_ tag the parent tag of _$the_legend_of_zelda_, which has the shorthand _tloz_ and the alias _the legend of zelda_. Then I tagged an image with only the _%princess_zelda_ tag.
When I search _princess zelda_ or _zelda_, the image shows up. But when I search _%princess_zelda_, it doesn't, meaning only the shorthand and the aliases of the tag are showing up in the search, and not the tag itself. When I search _totk_, the image shows up, but when I search _tears of the kingdom_ or _$tears_of_the_kingdom_, it doesn't, meaning only the shorthand of the parent tag is showing up in the search. When I search _tloz_ or _the legend of zelda_, the image shows up, but when I search _$the_legend_of_zelda_ it doesn't, meaning only the shorthand and the aliases of the grandparent tag are showing up in the search. 

However, this behavior differs slightly from the behavior of a different image that I tagged with a similar structure. The image is tagged only with _%gemma_, which has the shorthand _gemma_. _%gemma_ has the parent tag _$monster_hunter_wilds_, which has the shorthand _mhwilds_ and the alias _monster_hunter_wilds_. _$monster_hunter_wilds_ has the parent tag _$monster_hunter_, which has the shorthand _monster hunter_. 
When I search _gemma_ the image shows up, but it also shows up when I search _%gemma_, which is different from the first example, where searching the exact tag name did not return the image. When I search _mhwilds_ the image shows up, but not when I search _monster hunter wilds_ or _$monster_hunter_wilds_, which is identical behavior to the first example, where only the shorthand returned the image. But when I search _monster hunter_ or _$monster_hunter_, the image doesn't show up, which is different from the first example where searching the shorthand and aliases of the grandparent tag did return the image. 

For good measure, I tagged a third image to see if I could figure out any sort of pattern. The third image is tagged only with _%marina_, which has the shorthand _marina_. _%marina_ has the parent tag _$splatoon_2_, which has the shorthand _splatoon_2_. _$splatoon_2_ has the parent tag _$splatoon_, which has the shorthand _splatoon_. 
When I search _%marina_ or _marina_, the image shows up, which is the same as the second example. When I search _splatoon_2_ the image shows up, but not when I search _$splatoon_2_, which is the same as both examples. When I search _splatoon_ or _$splatoon_, the image shows up, which is different from both examples because searching the exact name of the grandparent tag did not return the image in the other examples. 

So in summary:
FIRST EXAMPLE
Tags (_%princess_zelda_, _zelda_, _princess zelda_): shorthand and alias return image. (2/3)
Parent Tags (_$tears_of_the_kingdom_, _totk_, _tears of the kingdom_): only shorthand returns image. (1/3)
Grandparent Tags (_$the_legend_of_zelda_, _tloz_, _the legend of zelda_): shorthand and alias return image. (2/3)

SECOND EXAMPLE
Tags (_%gemma_, _gemma_): exact name and shorthand return image. (2/2)
Parent Tags (_$monster_hunter_wilds_, _mhwilds_, _monster hunter wilds_): only shorthand returns image. (1/3)
Grandparent Tags (_$monster_hunter_, _monster hunter_): nothing returns image. (0/2)

THIRD EXAMPLE
Tags (_%marina_, _marina_): exact name and shorthand return image. (2/2)
Parent Tags (_$splatoon_2_, _splatoon 2_): only shorthand returns image. (1/2)
Grandparent Tags (_$splatoon_, _splatoon_): exact name and shorthand return image. (2/2)

Obviously this is a very small dataset, so take my analysis with a grain of salt, but here are the patterns I was able to identify:
-Tags with underscores never return the image.
-The only instances where searching the exact name of the tag returned the image was with tags that are one word and have no underscores. 
-Only the shorthand will return the image when searching parent tags.

The main thing that baffles me is how inconsistent the aliases with spaces are. I just have no idea why searching _the legend of zelda_ works, but _tears of the kingdom_ and _monster hunter wilds_ and _monster hunter_ don't. 
I'm not very familiar with coding, so I don't know what might be causing this, but hopefully this information is helpful for whenever the search function gets revamped.

### Expected Behavior

As for the expected behavior, I would expect an image to show up in the search if you search any of its tags, parent tags, or grandparent tags, etc, or if you search any of the shorthands/aliases of those tags, parent tags, or grandparent tags. 

### Steps to Reproduce

For the steps to reproduce, just create a few tags with parent and grandparent tags and give them shorthands and/or aliases. Maybe experiment with including symbols, underscores, and spaces. Then just tag some images with only the base tags and see whether they show up when you search certain parent tags and aliases.

**Comment by CyanVoxel** [comment] 2024-07-04 09:38
First off thank you so much for the in-depth explanation, this will *incredibly* helpful for narrowing this down 😁 

Some of this seems like it can be attributed to https://github.com/TagStudioDev/TagStudio/issues/112, wherein the search query is split along spaces. So searching for "monster hunter wilds" will be sent as three distinct queries, being "monster", "hunter", and "wilds". This is something that will be fixed down the line, but has slipped by for the time being.

As for some of the other cases, *hmm...* In your second example, I would definitely expect the grandparent "$monster_hunter" to return the "%gemma" tag. Likewise in your third example I would also expect "$splatoon_2" to return "%marina". Given that the grandparent tag in your third example somehow works as intended, my guess it that something might be wrong with how underscores are checked in the parser when it comes to tag relations. Behind the scenes, all characters such as underscores, hyphens, spaces, and apostophies are ignored while parsing (this is also responsible for the space bug).

I'll try to replicate this and further narrow in on the cause. Thank you again for the detailed bug report!

**Comment by Thesacraft** [comment] 2024-07-08 12:01
Hi I looked into this and I think I know why the bug is happening and CyanVoxel was on the right path :

It is partly due to the space bug, but that for example $tears_of_the_kingdom doesn't show the image taged with %princess_zelda is due to the parser ignoring underscores etc.. This is a problem because the search query is striped of punctuation ( including underscores ) and then the algorithm tries to find the matching tag to the query. For example the search query `$tears_of_the_kingdom` becomes `$tearsofthekingdom` but the tag name still is `$tears_of_the_kingdom` which means that the search is unsucsessfull. 

An easy fix would be to strip the punctuation of tags when they are created but this would also be displayed to the user ( meaning a tag created with the name `$tears_of_the_kingdom` would have the name `$tearsofthekingdom` after creation). I think using a striped version for the search part and displaying a non striped version to the user would be a bad idea because it could make it confusing to use and could end up making the code very confusing.

Theoretically #310 also removes this (and the space bug) but it is achieved by not stripping any punctuation at all. 
Personally I would remove the stripping of underscores regardless of the final solution for the rest because I think it makes it easier to read the tags if you can use underscores to separate words.

**Comment by CyanVoxel** [comment] 2024-12-07 00:19
Resolved as of #606, since that replaces the current search parser. Tag hierarchy search is yet to be re-implemented, however this bug is no longer applicable in the new parser

**Closed by CyanVoxel** 2024-12-07 00:19 UTC
Labels: Type: Bug, TagStudio: Tags, TagStudio: Search
