### ISSUE TITLE
[Feature Request]: a file manager style folder navigation

### ISSUE THREAD

**Issue by quakeman00** [TagStudioDev/TagStudio#501] opened 2024-09-13 19:00 UTC
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/docs/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### Description

could the file display to work with this be made in the style of a file manager similar to digikam where i can go up and down a folder hierarchy, so that unwarted files down the hierarchy of files aren't clogging up the files i actually want to work on.

### Solution

i already have a bunch of things in different folders i don't want to move around due to organization reason for uses for other programs, so by having a similar structure to go up and down folders to work on some specific files whitout having a bunchf of files i dont intend to work with (dll, exe, txt, ect) that are down the game's folder hiearchy

**Comment by CyanVoxel** [comment] 2024-09-13 20:10
Duplicate of #21

**Closed by CyanVoxel** 2024-09-13 20:10 UTC
Labels: Type: Duplicate, Type: Enhancement, Type: QoL, Type: UI/UX
