### ISSUE TITLE
[Feature Request]: Excluded folders

### ISSUE THREAD

**Issue by NotPubi** [TagStudioDev/TagStudio#385] opened 2024-08-24 14:25 UTC
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### Description

I am using this to organize my NAS and i have some things like uncompiled programs that have lots and lots of different kinds of files and tons of junk that i dont want showing up in my library

### Solution

An excluded folders option within a library would be excellent to fix this issue, similar to how obsidian has it set up in their system. This way these folders would simply not exist in the system.

### Alternatives

I am not sure what alternatives there may be to this, it seems to be a pretty cut and dry thing.

**Comment by KillyMXI** [comment] 2024-08-24 15:00
Programmers' way to do this is dot-ignore files. Most known example is `.gitignore`, but different apps use their own.

TagStudio, like Obsidian, has less technical audience and has to provide the UI, but would be great if underneath there is `.gitstudioignore` file with familiar [glob](https://en.wikipedia.org/wiki/Glob_(programming)) patterns.

**Comment by CyanVoxel** [comment] 2024-08-24 17:45
Duplicate of #14

**Closed by CyanVoxel** 2024-08-24 17:45 UTC
Labels: Type: Duplicate, Type: Enhancement, Type: File System
