### ISSUE TITLE
[Suggestion] Add base token structure for multiple translations

### ISSUE THREAD

**Issue by williamtcastro** [TagStudioDev/TagStudio#83] opened 2024-04-28 04:24 UTC
Great project, I think since has already a qt refactoring in place and in a alpha stages is a good idea to start adding the token structure for translations of the app

Also I speak Brazilian Portuguese.

**Comment by goldstargloww** [comment] 2024-04-28 04:43
i could help with a translation into [toki pona](https://sona.pona.la/wiki/Toki_Pona) :D! bit of an obscure one, sure, but conlangs are fun. i think it'd be a fun project

**Comment by smileyhead** [comment] 2024-05-01 13:56
I'd love to help with Hungarian.

**Comment by Qronikarz** [comment] 2024-05-02 16:35
I may help with Polishing the program.

**Comment by Amirhan-Taipovjan-Greatest-I** [comment] 2024-05-09 13:22
I also want to see Localization of this brand new App... so I can provide Tatar Translation.

**Comment by Nginearing** [comment] 2024-09-04 21:01
Hi all,   [ @williamtcastro, @goldstargloww, @smileyhead, @Qronikarz, @Amirhan-Taipovjan-Greatest-I ] 

We're currently discussing and experimenting with the localisation of TagStudio, to find the optimal service.

You can view the feature request page [here!](https://github.com/TagStudioDev/TagStudio/issues/446)

**Comment by Nginearing** [comment] 2024-09-24 19:26
Hi all, [ @williamtcastro, @goldstargloww, @smileyhead, @Qronikarz, @Amirhan-Taipovjan-Greatest-I ]

You are now able to translate Tag Studio into your language of choice at: https://hosted.weblate.org/engage/tagstudio/

Translation so far....
![multi-auto](https://github.com/user-attachments/assets/8525b049-7bd9-48bc-a262-9fb9ecfd98b2)

**Comment by williamtcastro** [comment] 2024-09-26 00:54
Awesome, I just created a account over to help :D

**Comment by Nginearing** [comment] 2024-09-26 14:58
> Awesome, Thank you @Nginearing, I just created a account over to help :D
> 
> Should we close the issue or keep it open?

Thank @Bamowen and @Tyrannicodin instead! 😆

If you could close the issue and put in the original issue post that the issue has been closed and that all correspondence about the issue is now taking place in #446, that would be great, thanks!

**Closed** 2024-09-26 18:55 UTC
Labels: Type: Enhancement, Type: Translation
