### ISSUE TITLE
Option to Display Tags as a Tree

### ISSUE THREAD

**Issue by Immac** [TagStudioDev/TagStudio#216] opened 2024-05-23 23:28 UTC
Add tree view as an option, you'd have to repeat the tags that have several parents (Which means it won't be a real tree but I digress), but it it should be more compact and less cluttered than a list when focused on only a specific part of the tag hierarchy.

**Comment by CyanVoxel** [comment] 2024-06-03 20:52
It's a great idea, but a duplicate of #19. I'm closing this one in favor of continuing the discussion over there

**Closed** 2024-06-03 20:52 UTC
Labels: duplicate
