### ISSUE TITLE
[Bug]: Create Tags from Folder not working

### ISSUE THREAD

**Issue by patelheet30** [TagStudioDev/TagStudio#404] opened 2024-08-27 10:41 UTC
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### TagStudio Version

Alpha 9.3.2

### Operating System & Version

macOS Sonoma 14.6

### Description

Facing 2 separate issues:

1) I tried using the Folders to Tag feature and it generated the Tags properly but couldn't apply them. Could manually add tags afterwards. **(Small Directory with around 150 items)**

2) I tried using the Folders to Tag feature and it generated the Tags properly but couldn't apply them. In addition to this, when closing out of the Apply window, when I try to manually add the tags, they don't show up. **(Large Directory with around 82k items)**

### Expected Behavior

Tags should be generated from Folders and then auto applied to all items.

### Steps to Reproduce

For Issue 1 (Small Directory):
1. Click on Folders to Tag
2. Click on Apply after tags are generated
3. They don't get applied
4. Try to manually add tag to an item
5. Tag shows up and can be added
---
For Issue 2 (Large Directory):
1. Click on Folders to Tag
2. Click on Apply after tags are generated
3. They don't get applied
6. Try to manually add tag to an item
7. Tag doesn't show up and can't be added

**Comment by yedpodtrzitko** [comment] 2024-08-29 15:39
Cant reproduce this. Running the application from shell to see the logs & provide them would be helpful.

**Comment by CyanVoxel** [comment] 2024-08-29 17:14
Duplicate of #346: FtT is broken in 9.3.2. Should be fixed in #347 for the next release

**Closed** 2024-09-01 01:14 UTC
Labels: Type: Bug, Type: Duplicate
