### ISSUE TITLE
[Feature Request]: Add List Mode

### ISSUE THREAD

**Issue by Teltt** [TagStudioDev/TagStudio#492] opened 2024-09-10 20:00 UTC
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/docs/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### Description

The grid view does not offer my preferred method of navigating large file systems, which is list mode/details mode, this is useful for identifying files that do not have thumbnails, displaying the window in a compressed corner, and quick navigation.

### Solution

Here is my suggestion for how list mode could be look, displayed in ubuntu fileviewer. The numbers at the beginning are for ordering and demonstration purposes.
![364895834-a5f1a38a-5753-45a7-b7aa-599175b0112f](https://github.com/user-attachments/assets/2743b2c4-c5d1-40c7-93ec-cae25076de09)

0 The sorting bar, similar to the sorting bar in file explorers, see the actual one in the screenshot that's above it.
1 tag navigation lists: These lists display tags that match the criteria of the current search and and all have relations to the current search... this is similar to how folders are displayed, but is more like a web of links. See alternatives for alternatives.
2 and 3 are for sorting the demonstration, they are effectively part of 2.
4, 5 and 6 is the file list.

### Alternatives

1 the navigation lists could match the current search or make a new search of that tag when clicked on. A navigation system is important for intuitive file management. In any case, please make it as flexible as possible, not just copying the standard file explorer solution but considering others.

Sibling tags are tags that fall under the same parent tag, match the current tag search options, or optionally have similar child tags. Please consider how to implement this most effectively.

**Comment by CyanVoxel** [comment] 2024-09-10 20:54
Duplicate of #62. Thank you for the wonderful description and visual example though, it's much more in-depth than the initial feature request for this. But I'm afraid I'm going to have to close this and nudge the conversation back over to #62.

**Closed by CyanVoxel** 2024-09-10 20:54 UTC
Labels: Type: Enhancement
